# Generated by Django 4.2.16 on 2024-10-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_created_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_projects',
            field=models.ManyToManyField(blank=True, related_name='member', to='projects.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('common', 'Common')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_projects',
            field=models.ManyToManyField(blank=True, related_name='requested', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
