# Generated by Django 4.2.16 on 2024-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_attendees_schedulemeet_participants_and_more"),
        ("users", "0002_user_custom_username_user_joined_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_projects",
            field=models.ManyToManyField(
                blank=True, related_name="member", to="projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="permission_level",
            field=models.CharField(
                choices=[("admin", "Admin"), ("owner", "Owner"), ("common", "Common")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="requested_projects",
            field=models.ManyToManyField(
                blank=True, related_name="requested", to="projects.project"
            ),
        ),
    ]
