# Generated by Django 4.2.16 on 2024-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeet',
            name='title',
            field=models.TextField(),
        ),
    ]
