# Generated by Django 4.2.16 on 2024-10-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='s3_url',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
