# Generated by Django 4.2.16 on 2024-11-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeet',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedulemeet',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
