# Generated by Django 4.2.16 on 2024-11-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
