# Generated by Django 4.2.16 on 2024-10-18 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulemeet",
            old_name="attendees",
            new_name="participants",
        ),
        migrations.RenameField(
            model_name="timeline",
            old_name="milestone",
            new_name="event",
        ),
        migrations.RemoveField(
            model_name="collaboration",
            name="content",
        ),
        migrations.RemoveField(
            model_name="fileupload",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="assigned_users",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="custom_labels",
        ),
        migrations.AddField(
            model_name="collaboration",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="title",
            field=models.CharField(default="Untitled Collaboration", max_length=200),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="file_name",
            field=models.CharField(default="Untitled File", max_length=255),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="s3_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creates_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="member_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="schedulemeet",
            name="end_time",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="schedulemeet",
            name="start_time",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="todo",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_todos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="schedulemeet",
            name="meeting_date",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.DeleteModel(
            name="TodoAssignment",
        ),
    ]
