# Generated by Django 4.2.16 on 2024-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='description',
            field=models.TextField(default='', help_text='Description of the file content'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_title',
            field=models.CharField(default='', help_text='Title for the file', max_length=255),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated list of keywords for the file'),
        ),
    ]
