# Generated by Django 4.2.16 on 2024-10-19 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_remove_fileupload_file_name_remove_fileupload_s3_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requested',
            field=models.ManyToManyField(blank=True, related_name='projects_requested_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
