# Generated by Django 4.2.16 on 2024-11-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_schedulemeet_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeet',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedulemeet',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
