# Generated by Django 4.2.16 on 2024-10-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_fileupload_description_fileupload_file_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='fileupload',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='projects.tag'),
        ),
    ]
