# Generated by Django 4.2.16 on 2024-11-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_schedulemeet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeet',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
