# Generated by Django 4.2.16 on 2024-10-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulemeet",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulemeet",
            name="meeting_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulemeet",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
