# Generated by Django 4.2.16 on 2024-10-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tag_fileupload_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
    ]
