# Generated by Django 4.2.16 on 2024-10-18 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_schedulemeet_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulemeet",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="schedulemeet",
            name="meeting_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="schedulemeet",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
