# Generated by Django 4.2.16 on 2024-10-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_tag_name_remove_tag_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'project')},
        ),
    ]
