# Generated by Django 4.2.16 on 2024-11-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_tag_unique_together_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemeet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='schedulemeet',
            name='participants',
        ),
    ]
