# Generated by Django 4.2.16 on 2024-11-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_schedulemeet_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeet',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedulemeet',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
